#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCBA54E245745D4EA (trevi55@gmail.com)
#
Name     : libdbusmenu
Version  : 16.04.0
Release  : 1
URL      : https://launchpad.net/libdbusmenu/16.04/16.04.0/+download/libdbusmenu-16.04.0.tar.gz
Source0  : https://launchpad.net/libdbusmenu/16.04/16.04.0/+download/libdbusmenu-16.04.0.tar.gz
Source99 : https://launchpad.net/libdbusmenu/16.04/16.04.0/+download/libdbusmenu-16.04.0.tar.gz.asc
Summary  : libdbusmenu-glib.
Group    : Development/Tools
License  : GPL-3.0 LGPL-2.1 LGPL-3.0
Requires: libdbusmenu-data
Requires: libdbusmenu-lib
Requires: libdbusmenu-bin
Requires: libdbusmenu-license
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(atk)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(x11)

%description
This is a small library designed to make sharing and displaying
of menu structures over DBus simple and easy to use.  It works
for both QT and GTK+ and makes building menus simple.

%package bin
Summary: bin components for the libdbusmenu package.
Group: Binaries
Requires: libdbusmenu-data
Requires: libdbusmenu-license

%description bin
bin components for the libdbusmenu package.


%package data
Summary: data components for the libdbusmenu package.
Group: Data

%description data
data components for the libdbusmenu package.


%package dev
Summary: dev components for the libdbusmenu package.
Group: Development
Requires: libdbusmenu-lib
Requires: libdbusmenu-bin
Requires: libdbusmenu-data
Provides: libdbusmenu-devel

%description dev
dev components for the libdbusmenu package.


%package doc
Summary: doc components for the libdbusmenu package.
Group: Documentation

%description doc
doc components for the libdbusmenu package.


%package lib
Summary: lib components for the libdbusmenu package.
Group: Libraries
Requires: libdbusmenu-data
Requires: libdbusmenu-license

%description lib
lib components for the libdbusmenu package.


%package license
Summary: license components for the libdbusmenu package.
Group: Default

%description license
license components for the libdbusmenu package.


%prep
%setup -q -n libdbusmenu-16.04.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534964118
%configure --disable-static --with-gtk=3 \
--disable-dumper
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1534964118
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libdbusmenu
cp COPYING %{buildroot}/usr/share/doc/libdbusmenu/COPYING
cp COPYING-GPL3 %{buildroot}/usr/share/doc/libdbusmenu/COPYING-GPL3
cp COPYING.2.1 %{buildroot}/usr/share/doc/libdbusmenu/COPYING.2.1
%make_install
## install_append content
make -C libdbusmenu-glib install DESTDIR=%{buildroot}
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/libexec/dbusmenu-bench
/usr/libexec/dbusmenu-testapp

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Dbusmenu-0.4.typelib
/usr/lib64/girepository-1.0/DbusmenuGtk3-0.4.typelib
/usr/share/gir-1.0/*.gir
/usr/share/libdbusmenu/json/test-gtk-label.json

%files dev
%defattr(-,root,root,-)
/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/client.h
/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/dbusmenu-glib.h
/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/enum-types.h
/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/menuitem-proxy.h
/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/menuitem.h
/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/server.h
/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/types.h
/usr/include/libdbusmenu-glib-0.4/libdbusmenu-jsonloader/json-loader.h
/usr/include/libdbusmenu-gtk3-0.4/libdbusmenu-gtk/client.h
/usr/include/libdbusmenu-gtk3-0.4/libdbusmenu-gtk/dbusmenu-gtk.h
/usr/include/libdbusmenu-gtk3-0.4/libdbusmenu-gtk/menu.h
/usr/include/libdbusmenu-gtk3-0.4/libdbusmenu-gtk/menuitem.h
/usr/include/libdbusmenu-gtk3-0.4/libdbusmenu-gtk/parser.h
/usr/lib64/libdbusmenu-glib.la
/usr/lib64/libdbusmenu-glib.so
/usr/lib64/libdbusmenu-gtk3.so
/usr/lib64/libdbusmenu-jsonloader.so
/usr/lib64/pkgconfig/dbusmenu-glib-0.4.pc
/usr/lib64/pkgconfig/dbusmenu-gtk3-0.4.pc
/usr/lib64/pkgconfig/dbusmenu-jsonloader-0.4.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libdbusmenu/*
/usr/share/gtk-doc/html/libdbusmenu-glib/annotation-glossary.html
/usr/share/gtk-doc/html/libdbusmenu-glib/api-index-deprecated.html
/usr/share/gtk-doc/html/libdbusmenu-glib/api-index-full.html
/usr/share/gtk-doc/html/libdbusmenu-glib/ch01.html
/usr/share/gtk-doc/html/libdbusmenu-glib/home.png
/usr/share/gtk-doc/html/libdbusmenu-glib/index.html
/usr/share/gtk-doc/html/libdbusmenu-glib/index.sgml
/usr/share/gtk-doc/html/libdbusmenu-glib/left-insensitive.png
/usr/share/gtk-doc/html/libdbusmenu-glib/left.png
/usr/share/gtk-doc/html/libdbusmenu-glib/libdbusmenu-glib-DbusmenuClient.html
/usr/share/gtk-doc/html/libdbusmenu-glib/libdbusmenu-glib-DbusmenuMenuitem.html
/usr/share/gtk-doc/html/libdbusmenu-glib/libdbusmenu-glib-DbusmenuMenuitemProxy.html
/usr/share/gtk-doc/html/libdbusmenu-glib/libdbusmenu-glib-DbusmenuServer.html
/usr/share/gtk-doc/html/libdbusmenu-glib/libdbusmenu-glib-Types.html
/usr/share/gtk-doc/html/libdbusmenu-glib/libdbusmenu-glib.devhelp2
/usr/share/gtk-doc/html/libdbusmenu-glib/object-tree.html
/usr/share/gtk-doc/html/libdbusmenu-glib/right-insensitive.png
/usr/share/gtk-doc/html/libdbusmenu-glib/right.png
/usr/share/gtk-doc/html/libdbusmenu-glib/style.css
/usr/share/gtk-doc/html/libdbusmenu-glib/up-insensitive.png
/usr/share/gtk-doc/html/libdbusmenu-glib/up.png
/usr/share/gtk-doc/html/libdbusmenu-gtk/annotation-glossary.html
/usr/share/gtk-doc/html/libdbusmenu-gtk/api-index-deprecated.html
/usr/share/gtk-doc/html/libdbusmenu-gtk/api-index-full.html
/usr/share/gtk-doc/html/libdbusmenu-gtk/ch01.html
/usr/share/gtk-doc/html/libdbusmenu-gtk/home.png
/usr/share/gtk-doc/html/libdbusmenu-gtk/index.html
/usr/share/gtk-doc/html/libdbusmenu-gtk/index.sgml
/usr/share/gtk-doc/html/libdbusmenu-gtk/left-insensitive.png
/usr/share/gtk-doc/html/libdbusmenu-gtk/left.png
/usr/share/gtk-doc/html/libdbusmenu-gtk/libdbusmenu-gtk-DbusmenuGtkClient.html
/usr/share/gtk-doc/html/libdbusmenu-gtk/libdbusmenu-gtk-DbusmenuGtkMenu.html
/usr/share/gtk-doc/html/libdbusmenu-gtk/libdbusmenu-gtk-menuitem.html
/usr/share/gtk-doc/html/libdbusmenu-gtk/libdbusmenu-gtk-parser.html
/usr/share/gtk-doc/html/libdbusmenu-gtk/libdbusmenu-gtk.devhelp2
/usr/share/gtk-doc/html/libdbusmenu-gtk/object-tree.html
/usr/share/gtk-doc/html/libdbusmenu-gtk/right-insensitive.png
/usr/share/gtk-doc/html/libdbusmenu-gtk/right.png
/usr/share/gtk-doc/html/libdbusmenu-gtk/style.css
/usr/share/gtk-doc/html/libdbusmenu-gtk/up-insensitive.png
/usr/share/gtk-doc/html/libdbusmenu-gtk/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdbusmenu-glib.so.4
/usr/lib64/libdbusmenu-glib.so.4.0.12
/usr/lib64/libdbusmenu-gtk3.so.4
/usr/lib64/libdbusmenu-gtk3.so.4.0.12
/usr/lib64/libdbusmenu-jsonloader.so.4
/usr/lib64/libdbusmenu-jsonloader.so.4.0.12

%files license
%defattr(-,root,root,-)
/usr/share/doc/libdbusmenu/COPYING
/usr/share/doc/libdbusmenu/COPYING-GPL3
/usr/share/doc/libdbusmenu/COPYING.2.1
